dataset: camelyon17
name: cam_student_mnv3s_scratch_v2
epochs: 10
batch_size: 128
lr: 0.01
weight_decay: 0.0001
train_subset: 100000
seed: 0
pretrained: true
model: mobilenetv3_small_100
kd:
  method: none
