name: iwc_student_mnv3s_kd_strongT
dataset: iwildcam
size: 224
epochs: 8
batch_size: 64
lr: 0.01
weight_decay: 0.0001
train_subset: 50000
seed: 0
pretrained: true
model: mobilenetv3_small_100
teacher_ckpt: runs_iwc/iwc_teacher_resnet50_strong/best.pt
kd:
  method: kd
  temperature: 4.0
  ce_weight: 0.1
  kd_weight: 0.9
  warmup_epochs: 0
