name: student_wrn_16_2_scratch
epochs: 240
batch_size: 64
lr: 0.05
weight_decay: 0.0005
augmix: false
seed: 0
schedule:
  type: multistep
  milestones:
  - 150
  - 180
  - 210
  gamma: 0.1
model: wrn_16_2
kd:
  method: none
